<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="4B2SDIC1DNCWGUX" name="com.example.cases.Index" tests="9" failures="0" timestamp="20 Feb 2017 14:26:41 GMT" time="43.095" errors="1">
  <testcase name="testSchool" time="2.806" classname="com.example.cases.Index"/>
  <testcase name="testNoticeCenter" time="1.627" classname="com.example.cases.Index"/>
  <testcase name="testIntentcare" time="0.450" classname="com.example.cases.Index"/>
  <testcase name="Login" time="12.314" classname="com.example.cases.Index"/>
  <testcase name="testExpertSearch" time="1.565" classname="com.example.cases.Index"/>
  <testcase name="testSchoolTab" time="8.648" classname="com.example.cases.Index"/>
  <testcase name="testMain" time="7.082" classname="com.example.cases.Index"/>
  <testcase name="testPersonCenter" time="1.764" classname="com.example.cases.Index"/>
  <testcase name="testInspection" time="6.839" classname="com.example.cases.Index">
    <error type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at 
报错信息: 自查是否正常显示 expected [true] but found [false].
报错方法名:testInspection(
报错类:Index
报错行号:95)
	at com.example.cases.Index.testInspection(Index.java:95)
]]>
    </error>
  </testcase> <!-- testInspection -->
</testsuite> <!-- com.example.cases.Index -->
